### ISSUE TITLE
Support for GEMS + SPATIAL 

### ISSUE THREAD

**Issue by RadhaGulhane13** [OSU-Nowlab/MPI4DL#12]
**Overview:** 
Release-0.5 commit(https://github.com/OSU-Nowlab/MPI4DL/commits/main) supports GEMS and Spatial design , but the Hybrid model (GEMS + SPATIAL) is not supported. 

**Description:**
- AmoebaNet model with GEMS + SPATIAL is hanging during training step. Specifically, second model replica of GEMS is not able to complete forward pass.
- Support for ResNet model with GEMS + SPATIAL is not currently implemented.

**Comment by Quentin-Anthony** [comment]
Resolved by https://github.com/OSU-Nowlab/MPI4DL/pull/14
